# Etapa 1: build
FROM node:18-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Etapa 2: servir el frontend con Nginx
FROM nginx:alpine

# Copiamos los archivos de build a la carpeta pública de Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Reemplazamos la configuración default de Nginx (opcional)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
